name:                aoc2016
version:             2016.0
github:              "jodeen/advent-2016"
license:             BSD3
author:              "James Odeen"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:        Advent of Code 2016

dependencies:
- base >= 4.7 && < 5
- time
- ansi-terminal
- directory
- optparse-applicative
- parser-combinators
- attoparsec
- containers
- text
- mtl
- vector
- pureMD5

library:
  source-dirs: src
  default-extensions:
    - LambdaCase
    - MultiWayIf
    - RecordWildCards
    - OverloadedRecordDot
    - OverloadedStrings
    - GADTs
    - GHC2021

executables:
  aoc-template-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N4
    - -with-rtsopts=-qa
    - -with-rtsopts=-C0
    - -funfolding-use-threshold=16
    - -fexcess-precision
    - -optc-O3
    - -optc-ffast-math
    - -O2
    default-extensions:
    - LambdaCase
    - MultiWayIf
    - RecordWildCards
    - OverloadedRecordDot
    - OverloadedStrings
    - GADTs
    - GHC2021
    dependencies:
    - aoc2016
